"""add feedback and user

Revision ID: 51c76f48f259
Revises: 
Create Date: 2026-02-04 19:53:47.227861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c76f48f259'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.CheckConstraint("type IN ('review','suggestion')", name='feedback_type_check'),
    sa.CheckConstraint('rating BETWEEN 1 AND 10', name='rating_range_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_name'), 'feedbacks', ['name'], unique=False)
    op.create_index(op.f('ix_feedbacks_is_approved'), 'feedbacks', ['is_approved'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_feedbacks_is_approved'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_name'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
